### ISSUE TITLE
add a comma in __all__ section of  `/home/runner/work/embetter/embetter/embetter/text/__init__.py`

### ISSUE THREAD

**Issue by anopsy** [koaning/embetter#101]
also I would like to know how to prevent this from happenig in the future, I've run the tests, but they clearly don't cover that, also the checks don't happen during a commit (As in scikit-learn) so I could definitely use some hint on how to check if there's no bug in the code I commit

**Comment by koaning** [comment]
I would need a slightly more elaborate issue to understand what is happening. 

Why do you need to add a comma to the file? Could you elaborate on what is currently wrong with the file?

**Comment by anopsy** [comment]
![Screenshot_20240422_130559_Chrome](https://github.com/koaning/embetter/assets/74981211/25a11b23-4188-4b08-b8b4-0ae01c524ec1)
Sure. I noticed that when you accepted my PR it actually failed due to a check from Black. if that makes any sense and it looks like its because of the missing comma after MatryoshkaEncoder.

**Comment by koaning** [comment]
Ahh, I must've merged it in a hurry without waiting for the CI to run. That's on me. Feel free to whip up a new PR with a fix if you like but I can also fix it later.

Thanks for the ping either way. :)

**Comment by anopsy** [comment]
I'll do that
