### ISSUE TITLE
Add progressbar to all slow models. 

### ISSUE THREAD

**Issue by koaning** [koaning/embetter#20]
A sign of life is appreciated.

**Comment by koaning** [comment]
I'm still a bit on the fence about this one. Feel free to try out a progress bar, but maybe also track the inference speed. Preferably with [perfplot](https://calmcode.io/shorts/perfplot.html).

**Comment by CarloLepelaars** [comment]
Created a draft for this and tried to keep verbosity down as much as possible. Let me know what you think! Will check out perfplot. 

https://github.com/koaning/embetter/pull/28
