### ISSUE TITLE
Remove the classification layer in timm models

### ISSUE THREAD

**Issue by kacperlukawski** [koaning/embetter#21]
I was playing a bit with the library and found out that the `TimmEncoder` returns 1000-dimensional vectors for all the models I selected. That is caused by returning the state of the last FC classification layer and the fact all of the models were trained on ImageNet with 1000 classes. In practice, it's typically replaced with identity.

Are there any reasons for returning the state of that last layer as an embedding? I'd be happy to submit a PR fixing that.

**Comment by koaning** [comment]
Really? Oh, that's odd, I thought I had been following the guide [here](https://rwightman.github.io/pytorch-image-models/feature_extraction/), but you're right. I should be using the `forward_features` call there. That said, it's still a representation of the image that is useful for visualization/ training your own layer on top of. 

I would welcome a PR for sure, but I would prefer it if any PR would allow the users to pick either the classification layer or the hidden layer just before it with a parameter. Something like `use_clf_layer=True/False`? I'm open to a better name, though.
