### ISSUE TITLE
[FEATURE] SpaCyEmbedder

### ISSUE THREAD

**Issue by CarloLepelaars** [koaning/embetter#27]
I think it would be a nice addition to add an embedder that can easily vectorize text through SpaCy. I already have an implementation class for this and would be happy to contribute it here.

SpaCy Docs on vector:
https://spacy.io/api/doc#vector

Example code for single string:
```python
import spacy
nlp = spacy.load("en_core_web_sm")
doc = nlp("This here text")
doc.vector
```

**Comment by CarloLepelaars** [comment]
Ok, no problem! Will check out whatlies.

**Comment by koaning** [comment]
There may yet be reasons to add these embeddings. Not 100% sure, but enough doubt to re-open this issue. In particular I might want to think about adding support for spacy and bytepair embeddings. Will be doing entity stuff soon.
