### ISSUE TITLE
clip support

### ISSUE THREAD

**Issue by koaning** [koaning/embetter#3]
https://www.sbert.net/examples/applications/image-search/README.html

**Comment by wjbmattingly** [comment]
This would be really nice to see. I already know of a project at SI that would benefit from this. I am going to share it on our slack to see if there is interest here.

**Comment by koaning** [comment]
This is automatically supported via the `SentenceTransformer` feature. Interestingly enough, it seems to be able to detect if an `PIL.Image` object is passed. 

Need to think if it's worth a separate class, though. But if you can confirm a nice use-case I'll gladly add it.

**Comment by koaning** [comment]
I confirmed a week ago that CLIP is implemented as-in by sentence transformers. 

I might implement a convenience method for CLIP. But it's not required. Just pass PIL objects to get embeddings for images and text to get the same for text.
